source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

target 'WLKit_Example' do
  pod "WLKit", :path => "../"
end

target 'WLKit_Tests' do
  pod "WLKit", :path => "../"

#  pod 'FBSnapshotTestCase'
end
